### ISSUE TITLE
Light/Dark mode toggle icon cut off 

### ISSUE THREAD

**Issue by 12vanblart** [Microflash/jada#1]
It looks like the area for the icon to display is smaller than the icon being drawn: 

![Icon being cut off in lower right corner](https://user-images.githubusercontent.com/16465776/71112262-1e487780-2199-11ea-96bb-653bbc9ace4b.png)

I'm not very familiar with SVGs, but it looks like setting the `.icon` class to a `width` and `height` of `2rem` would resolve this.

**Comment by Microflash** [comment]
This seems to be happening because of `viewbox` not been properly set for some of the SVGs. I have refactored all the icons with proper `viewbox` (ca04016670629c97e24079d5763395fbc3d0aa18) that should fix this.
